export const enhanceDefaults = [
  { key: 'rate_0_to_1', value: { rate: 1.0, failPenalty: 'none' }, description: '+0 → +1 강화 확률' },
  { key: 'rate_1_to_2', value: { rate: 0.95, failPenalty: 'none' }, description: '+1 → +2 강화 확률' },
  { key: 'rate_2_to_3', value: { rate: 0.9, failPenalty: 'none' }, description: '+2 → +3 강화 확률' },
  { key: 'rate_3_to_4', value: { rate: 0.85, failPenalty: 'none' }, description: '+3 → +4 강화 확률' },
  { key: 'rate_4_to_5', value: { rate: 0.75, failPenalty: 'none' }, description: '+4 → +5 강화 확률' },
  { key: 'rate_5_to_6', value: { rate: 0.65, failPenalty: 'none' }, description: '+5 → +6 강화 확률' },
  { key: 'rate_6_to_7', value: { rate: 0.55, failPenalty: 'none' }, description: '+6 → +7 강화 확률' },
  { key: 'rate_7_to_8', value: { rate: 0.45, failPenalty: 'none' }, description: '+7 → +8 강화 확률' },
  { key: 'rate_8_to_9', value: { rate: 0.40, failPenalty: 'none' }, description: '+8 → +9 강화 확률' },
  { key: 'rate_9_to_10', value: { rate: 0.35, failPenalty: 'none' }, description: '+9 → +10 강화 확률' },
  { key: 'rate_10_to_11', value: { rate: 0.30, failPenalty: 'downgrade_1' }, description: '+10 → +11 강화 확률' },
  { key: 'rate_11_to_12', value: { rate: 0.25, failPenalty: 'downgrade_1' }, description: '+11 → +12 강화 확률' },
  { key: 'rate_12_to_13', value: { rate: 0.20, failPenalty: 'downgrade_1' }, description: '+12 → +13 강화 확률' },
  { key: 'rate_13_to_14', value: { rate: 0.17, failPenalty: 'downgrade_1' }, description: '+13 → +14 강화 확률' },
  { key: 'rate_14_to_15', value: { rate: 0.15, failPenalty: 'downgrade_1' }, description: '+14 → +15 강화 확률' },
  { key: 'rate_15_to_16', value: { rate: 0.12, failPenalty: 'downgrade_2' }, description: '+15 → +16 강화 확률' },
  { key: 'rate_16_to_17', value: { rate: 0.10, failPenalty: 'downgrade_2' }, description: '+16 → +17 강화 확률' },
  { key: 'rate_17_to_18', value: { rate: 0.07, failPenalty: 'destroy' }, description: '+17 → +18 강화 확률' },
  { key: 'rate_18_to_19', value: { rate: 0.05, failPenalty: 'destroy' }, description: '+18 → +19 강화 확률' },
  { key: 'rate_19_to_20', value: { rate: 0.03, failPenalty: 'destroy' }, description: '+19 → +20 강화 확률' },
  { key: 'cost_multiplier', value: { baseGold: 100, perLevel: 1.5 }, description: '강화 비용 계수(골드 전용)' },
];
